[package]
name = "rust-self-education"
version = "0.1.0"
authors = ["Dmitry Galashin <MustangDSG@ya.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
